#!/bin/sh -e

[ -z $7 ] && \
  echo $0': <ip> <port> <iface> <tun_addr> <gateway> <ptp> <passwd>' 1>&2 && \
  exit 64

mkdir -p /services/tunserver-$3 || exit 255
mkdir -p /services/tunserver-$3/env || exit 255

echo $1 > /services/tunserver-$3/env/IP || exit 255
echo $2 > /services/tunserver-$3/env/PORT || exit 255
echo $3 > /services/tunserver-$3/env/INTERFACE || exit 255
echo $4 > /services/tunserver-$3/env/TUN_ADDR || exit 255
echo $5 > /services/tunserver-$3/env/GATEWAY || exit 255
echo $6 > /services/tunserver-$3/env/PTP || exit 255
echo $7 > /services/tunserver-$3/env/PASSWD || exit 255

ln -s `pwd`/tun /services/tunserver-$3/tun
ln -s `pwd`/run.tunserver /services/tunserver-$3/run
ln -s `pwd`/tunserver /services/tunserver-$3/tunserver
ln -s `pwd`/recvpasswd /services/tunserver-$3/recvpasswd
ln -s `pwd`/ifup-server.sh /services/tunserver-$3/ifup-server.sh

test -L /service/tunserver-$3 || ln -s /services/tunserver-$3 /service/tunserver-$3
