#!/bin/sh -e

[ -z $9 ] && \
  echo $0': <ip> <port> <iface> <tun_addr> <gateway> <ptp> <server> <extension> <curvecpserverpubkey>' 1>&2 && \
  exit 64

mkdir -p /services/tunclient-curvecp-$3 || exit 255
mkdir -p /services/tunclient-curvecp-$3/env || exit 255

echo $1 > /services/tunclient-curvecp-$3/env/IP || exit 255
echo $2 > /services/tunclient-curvecp-$3/env/PORT || exit 255
echo $3 > /services/tunclient-curvecp-$3/env/INTERFACE || exit 255
echo $4 > /services/tunclient-curvecp-$3/env/TUN_ADDR || exit 255
echo $5 > /services/tunclient-curvecp-$3/env/GATEWAY || exit 255
echo $6 > /services/tunclient-curvecp-$3/env/PTP || exit 255
echo $7 > /services/tunclient-curvecp-$3/env/SERVER || exit 255
echo $8 > /services/tunclient-curvecp-$3/env/EXTENSION || exit 255
echo $9 > /services/tunclient-curvecp-$3/env/CURVECPSERVERPUBKEY || exit 255

ln -s `pwd`/tun /services/tunclient-curvecp-$3/tun
ln -s `pwd`/tunclient /services/tunclient-curvecp-$3/tunclient
ln -s `pwd`/run.tunclient-curvecp /services/tunclient-curvecp-$3/run
ln -s `pwd`/ifup-client.sh /services/tunclient-curvecp-$3/ifup-client.sh

curvecpmakekey /services/tunclient-curvecp-$3/curvecp
find /services/tunclient-curvecp-$3/curvecp -type d -exec chmod 700 {} \;
find /services/tunclient-curvecp-$3/curvecp -type f -exec chmod 600 {} \;
chmod 700 /services/tunclient-curvecp-$3/curvecp
printf "CURVECPCLIENTPUBKEY: `curvecpprintkey /services/tunclient-curvecp-$3/curvecp`\n"

test -L /service/tunclient-curvecp-$3 || ln -s /services/tunclient-curvecp-$3 /service/tunclient-curvecp-$3
