#!/bin/sh -e

[ -z $6 ] && \
  echo $0': <ip> <port> <iface> <tun_addr> <gateway> <ptp>' 1>&2 && \
  exit 64

mkdir -p /services/tunclient-tor-$3 || exit 255
mkdir -p /services/tunclient-tor-$3/env || exit 255

echo $1 > /services/tunclient-tor-$3/env/IP || exit 255
echo $2 > /services/tunclient-tor-$3/env/PORT || exit 255
echo $3 > /services/tunclient-tor-$3/env/INTERFACE || exit 255
echo $4 > /services/tunclient-tor-$3/env/TUN_ADDR || exit 255
echo $5 > /services/tunclient-tor-$3/env/GATEWAY || exit 255
echo $6 > /services/tunclient-tor-$3/env/PTP || exit 255

ln -s `pwd`/tun /services/tunclient-tor-$3/tun
ln -s `pwd`/tunclient /services/tunclient-tor-$3/tunclient
ln -s `pwd`/run.tunclient-tor /services/tunclient-tor-$3/run
ln -s `pwd`/ifup-client.sh /services/tunclient-tor-$3/ifup-client.sh
ln -s `pwd`/ucspi-socks4aclient /services/tunclient-tor-$3/ucspi-socks4aclient

test -L /service/tunclient-tor-$3 || ln -s /services/tunclient-tor-$3 /service/tunclient-tor-$3
