#!/bin/sh -e

[ -z $7 ] && \
  echo $0': <ip> <port> <iface> <tun_addr> <gateway> <ptp> <passwd>' 1>&2 && \
  exit 64

mkdir -p /services/tunclient-$3 || exit 255
mkdir -p /services/tunclient-$3/env || exit 255

echo $1 > /services/tunclient-$3/env/IP || exit 255
echo $2 > /services/tunclient-$3/env/PORT || exit 255
echo $3 > /services/tunclient-$3/env/INTERFACE || exit 255
echo $4 > /services/tunclient-$3/env/TUN_ADDR || exit 255
echo $5 > /services/tunclient-$3/env/GATEWAY || exit 255
echo $6 > /services/tunclient-$3/env/PTP || exit 255
echo $7 > /services/tunclient-$3/env/PASSWD || exit 255
echo 1438 > /services/tunclient-$3/env/MTU || exit 255

chmod 700 /services/tunclient-$3/env/ || exit 255

ln -s `pwd`/tun /services/tunclient-$3/tun
ln -s `pwd`/run.tunclient /services/tunclient-$3/run
ln -s `pwd`/tunclient /services/tunclient-$3/tunclient
ln -s `pwd`/sendpasswd /services/tunclient-$3/sendpasswd
ln -s `pwd`/ifup-client.sh /services/tunclient-$3/ifup-client.sh

test -L /service/tunclient-$3 || ln -s /services/tunclient-$3 /service/tunclient-$3
